[project]
name = "idaes-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "coolprop>=7.2.0",
    "idaes-pse>=2.10.0",
    "ahuora-compounds",
    "idaes-ui>=0.25.10",
    "ahuora-builder-types==0.1.9",
    "ahuora-builder==0.1.9",
    "mcp>=1.13.0",
    "pyvis>=0.3.2",
    "conopt>=4.39.0",
    "amplpy>=0.16.0",
    "pip>=26.0.1",
]


[tool.uv.sources]
ahuora-compounds = { path= "../Ahuora-Adaptive-Digital-Twin-Platform/backend/ahuora-compounds", editable = true }
# Git clone ahuora-builder: https://github.com/waikato-ahuora-smart-energy-systems/ahuora-builder
ahuora-builder = { path = "../Ahuora-Adaptive-Digital-Twin-Platform/backend/ahuora-builder", editable = true }
ahuora-builder-types = { path = "../Ahuora-Adaptive-Digital-Twin-Platform/backend/ahuora-builder-types", editable = true }

[dependency-groups]
dev = [
    "ipython>=9.10.0",
]
